Algoritmo "semnome"
// Descrição   : Aula 2
// Data atual  : 17/12/2025
Var

  variavel1 : inteiro
  // Inteiro = so pode ser usado em numeros Inteiros
  variavel2 : real
  // real = recomendado para numeros reais (ou seja com virgulas porem virgula é retratada por .) e pode ser usada para numero inteiro mas n é recomendado.
  variavel3 : caracter
  // caracter = é utilizado para letras, palavras, nomes ou frases
  variavel4 : logico
  // logico = é usado para definir logicas no caso verdadeiro ou falso

Inicio

  variavel1 := 2302
  variavel2 := 342.3242
  variavel3 := "Louvado seja Deus"
  variavel4 := falso

  variavel1 := 0
  
  escreval(variavel1)
  escreval(variavel2)
  escreval(variavel3)
  escreval(variavel4)
  
  leia(variavel1)
  escreval(variavel1)
Fimalgoritmo
