algoritmo "semnome"
// Função :
// Autor :
// Data : 17/12/2025
// Seção de Declarações 
var
  Ano, Nascimento, Idade : inteiro
  Altura : real
  Nome : caracter
  
inicio

  escreval("Digite sua data de nascimento")
  leia(Nascimento)
  
  escreval("Digite o ano atual")
  leia(Ano)

  escreval("Digite sua altura")
  leia(Altura)
  
  escreval("Digite seu nome")
  leia(Nome)

  Idade := Ano - Nascimento

  escreval("Olá")
  escreval(nome)
  escreval (Altura)
  escreval(Idade)
fimalgoritmo
