algoritmo "semnome"
// Função :
// Autor :
// Data : 20/12/2025
// Seção de Declarações 
var
 valor : inteiro

inicio
 escreval("Digite o número equivalente a um mês (1 à 12)")
 leia(valor)
 
 se valor = 1 entao
   escreval("Mês de Janeiro")
 senao
   se valor = 2 entao
     escreval("Mês de Fevereiro")
   senao
     se valor = 3 entao
       escreval("Mês de Março")
     senao
       se valor = 4 entao
         escreval("Mês de Abril")
       senao
         se valor = 5 entao
           escreval("Mês de Maio")
         senao
           se valor = 6 entao
             escreval("Mês de Junho")
           senao
             se valor = 7 entao
               escreval("Mês de Julho")
             senao
               se valor = 8 entao
                 escreval("Mês de Agosto")
               senao
                 se valor = 9 entao
                   escreval("Mês de Setembro")
                 senao
                   se valor = 10 entao
                     escreval("Mês de Outubro")
                   senao
                     se valor = 11 entao
                       escreval("Mês de Novembro")
                     senao
                       se valor = 12 entao
                         escreval("Mês de Dezembro")
                       senao
                       fimse
                     fimse
                   fimse
                 fimse
               fimse
             fimse
           fimse
         fimse
       fimse
     fimse
   fimse
 fimse


fimalgoritmo
