algoritmo "Informar se é maior ou menor de idade"
// Função :
// Autor :
// Data : 08/03/2026
// Seção de Declarações
var
  idade :inteiro
inicio

para x de 1 ate 75 faca

   escreval("informe a idade da pessoa numero: ", " ", x)
   leia(idade)
   se (idade >= 18)  entao
     escreval("Você é maior de idade")
   senao
     se (idade <= 18) entao
       escreval("Você é menor de idade")
     fimse
   fimse
 fimpara

fimalgoritmo
