algoritmo "semnome"
// Função :
// Autor :
// Data : 20/12/2025
// Seção de Declarações 
var
 num1, num2 : real
inicio
 escreval("digite o primeiro numero")
 leia(num1)
 
 escreval("digite o segundo numero")
 leia(num2)
 
 se num1 = num2 entao
   escreval("Os 2 valores são iguais")
 senao
   se num1 > num2 entao
     escreval("O maior numero é:",(num1))
   senao
     escreval("O maior numero é:",(num2))
   fimse
 fimse
fimalgoritmo

