algoritmo "semnome"
// calculadora de 2 numeros
var
num1, num2, soma, sub, mult, divi : real


inicio

escreval("digite uo primeiro numero")
leia(num1)

escreval("digite o segundo numero")
leia(num2)

soma := num1 + num2
sub := num1 - num2
mult := num1 * num2
divi := num1 / num2

escreval("A soma é")
escreval(soma)

escreval("A subtração é")
escreval(sub)

escreval("A multiplicação é")
escreval(mult)

escreval("A divisão é")
escreval(divi)

fimalgoritmo
